Repository MOV-AI/movai-flow, pull requests merged in 2022-05, with the labels that each got.

#114 FP-1762 : Update Front-end app versions for CE
  .env
Labels: Status: In progress, front-end

#109 Feat: ppa public
  .github/workflows/DeployOnGitRelease.yml
  .github/workflows/TestOnPR.yml
  docker-compose.yml
Labels: enhancement, devops

#110 DP-686 : Fix recreated containers on reboot
  debian/install
  debian/movai-flow.postinst
  debian/movai-flow.prerm
  docker-compose.yml
  misc/movai-flow.service
  scripts/movai-flow-launch
Labels: devops

#116 Add issue template
  .github/ISSUE_TEMPLATE.md
Labels: enhancement

#112 Pre-release 1.2.0-2
  .env
  .github/ISSUE_TEMPLATE.md
  .github/workflows/DeployOnGitRelease.yml
  .github/workflows/TestOnPR.yml
  .gitignore
  README.md
  debian/.debhelper/generated/movai-flow/installed-by-dh_install
  debian/control
  debian/debhelper-build-stamp
  debian/install
  debian/movai-flow.debhelper.log
  debian/movai-flow.postinst
  debian/movai-flow.postrm
  debian/movai-flow.preinst
  debian/movai-flow.prerm
  debian/movai-flow.substvars
  docker-compose-nvidia.yml
  docker-compose.yml
  misc/movai-flow-cli.desktop
  misc/movai-flow-rviz.desktop
  misc/movai-flow-sim.desktop
  misc/movai-flow.desktop
  misc/movai-flow.service
  scripts/movai-flow-cli
  scripts/movai-flow-launch
  scripts/movai-flow-rviz
  scripts/movai-flow-simulator
  scripts/movai-flow-stop
Labels: pre-release

#138 Release 1.2.0-4
  .env
  docker-compose.yml
Labels: release

#148 Stop exposing ros-master port and better health check
  docker-compose.yml
Labels: bug
