Repository MOV-AI/movai-flow, pull requests merged in 2023-07, with the labels that each got.

#217 Minor updates
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/TestOnPR.yml
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation, devops

#225 Dp-1104 update service settings in docker compose
  .env
  .github/workflows/TestOnPR.yml
  docker-compose-host.yml
  docker-compose.yml
  scripts/movai-flow-launch
Labels: enhancement, 4.0.0

#224 Update README, add --all arg to movai-flow-reset script
  README.md
  scripts/movai-flow-reset
Labels: documentation, enhancement
